DELIMITER //
CREATE PROCEDURE `SP_BUSCAR_DETALLE_PERFIL`(
	XID_EMPRESA INT,
    XID_MODULO INT,
    XID_PERFIL INT
)
BEGIN
	SELECT
		F.FLG_PERMISO,
		A.ID_MODULOS,
		C.DESCRIPCION AS MODULO,
		A.ID_MENU,
		D.DESCRIPCION AS MENU,
		A.ID_SUBMENU,
		E.DESCRIPCION AS SUBMENU
	FROM	MENU_SUBMENU AS A
		INNER JOIN EMPRESA_MODULOS AS B ON  B.ID_MODULOS = A.ID_MODULOS
		INNER JOIN MODULOS AS C ON C.ID = A.ID_MODULOS
		INNER JOIN MENU AS D ON D.ID = A.ID_MENU
		INNER JOIN SUBMENU AS E ON E.ID = A.ID_SUBMENU
		LEFT JOIN DETALLE_PERFIL AS F ON F.ID_SUBMENU = A.ID_SUBMENU
		AND
		B.ID_EMPRESA = XID_EMPRESA AND A.ID_MODULOS=XID_MODULO AND F.ID_PERFIL= XID_PERFIL
	WHERE
		B.ID_EMPRESA=XID_EMPRESA AND C.ID=XID_MODULO;
END;
//
