/*
 * Una tabla temporal es una fotografía instantánea y estática de alguna parte de la base de datos, tomada cuando se ejecuta
 * su instrucción select de definición de SQL
*/
DELIMITER $$
CREATE PROCEDURE SP_DE_IMPRESION(
	XID_EMPRESA INT,
  XDOCUMENTO_VENTA_ID INT
)
BEGIN

	DECLARE DONE INT DEFAULT 0;

  -- RECOGE CODIGO Y POSICION DE DATOS DE LA CABECERA
  DECLARE COD VARCHAR(10);
  DECLARE POSI_X INT;

	-- CURSOR DE CABECERA
	DECLARE CURSOR_EJE_Y CURSOR FOR
		SELECT
			B.CODIGO,
			A.POSISION_X
		FROM IMP_CONFIGURACION_CAMPOS AS A
				INNER JOIN IMP_MAPEO_CAMPOS AS B ON B.ID_MAPEO_CAMPOS = A.ID_MAPEO_CAMPOS
		WHERE
				A.ID_TIPO_DOCUMENTO=1 AND A.SERIE = '001' AND A.ID_EMPRESA=XID_EMPRESA AND B.REGION='CABECERA'
		ORDER BY A.POSISION_Y,A.POSISION_X;

  -- TABLA TEMPORAL QUE CONTIENE EL LISTADO GENERAL DE IMPRESION
	CREATE TEMPORARY TABLE TMP_IMPRESION(
		DESCRIPCION VARCHAR(1000)
	);

  -- INICIALIZAMOS LA TABLA PARA PODER CONCATENAR
  INSERT INTO TMP_IMPRESION(DESCRIPCION) VALUES('');


  -- ABRIMOS EL CURSOR DE DATOS DE CABECERA
	OPEN CURSOR_EJE_Y;
		BUCLE: LOOP

      FETCH CURSOR_EJE_Y INTO COD,POSI_X;

      IF DONE = 1 THEN
				LEAVE BUCLE;
			END IF;

      -- ACTUALIZAMOS EL REGISTRO EN TABLA TEMPORAL
			UPDATE TMP_IMPRESION SET DESCRIPCION =  CONCAT(DESCRIPCION,CONCAT(SPACE(POSI_X),'^',COD));

		END LOOP BUCLE;
	CLOSE CURSOR_EJE_Y;

END$$
